"""Deterministic Canvas Common Cartridge generator for offline course imports."""
from __future__ import annotations
import hashlib, json, shutil, zipfile
from pathlib import Path
from xml.etree import ElementTree as ET
from .util import resolve_path, slugify

IMS = "http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1"
CANVAS = "http://canvas.instructure.com/xsd/cccv1p0"
ET.register_namespace("", IMS)

def _id(prefix, key): return prefix + hashlib.sha256(key.encode()).hexdigest()[:32]
def _sub(parent, tag, text=None, **attrs):
    e=ET.SubElement(parent, tag, attrs)
    if text is not None: e.text=str(text)
    return e
def _xml(root): return ET.tostring(root, encoding="utf-8", xml_declaration=True)
def _read(engine, value): return resolve_path(engine, value).read_text(encoding="utf-8")

def build_imscc(spec: dict, engine: Path, work: Path, output: Path) -> dict:
    """Build a Canvas-flavoured Common Cartridge from a JSON-compatible spec."""
    course=spec["course"]; title=course["title"]; course_id=_id("course", title)
    (work/"course_settings").mkdir(parents=True); (work/"wiki_content").mkdir()
    resources=[]; objects={}; module_refs=[]

    # Canvas course settings and assignment-group weights.
    cs=ET.Element("course", {"xmlns":CANVAS,"identifier":course_id})
    for tag,val in [("title",title),("course_code",course.get("course_code","")),
                    ("is_public","false"),("allow_student_wiki_edits","false"),
                    ("default_view",course.get("default_view","modules"))]: _sub(cs,tag,val)
    if course.get("front_page"): _sub(cs,"front_page_url",course["front_page"])
    _sub(cs,"license",course.get("license","private"))
    (work/"course_settings/course_settings.xml").write_bytes(_xml(cs))
    groups=ET.Element("assignmentGroups",{"xmlns":CANVAS})
    group_ids={}
    for pos,g in enumerate(spec.get("assignment_groups",[]),1):
        gid=_id("ag",g["title"]); group_ids[g["title"]]=gid
        ge=_sub(groups,"assignmentGroup",identifier=gid)
        _sub(ge,"title",g["title"]); _sub(ge,"position",pos); _sub(ge,"group_weight",g.get("weight",0))
    (work/"course_settings/assignment_groups.xml").write_bytes(_xml(groups))
    (work/"course_settings/canvas_export.txt").write_text("Generated by Canvas Automation\n")
    rubrics=ET.Element("rubrics",{"xmlns":CANVAS}); rubric_ids={}
    for rubric in spec.get("rubrics",[]):
        rid=_id("rubric",rubric["key"]); rubric_ids[rubric["key"]]=rid
        re=_sub(rubrics,"rubric",identifier=rid); _sub(re,"title",rubric["title"])
        _sub(re,"context_code","course"); _sub(re,"reusable",str(rubric.get("reusable",False)).lower()); _sub(re,"public","false")
        _sub(re,"points_possible",sum(float(c["points"]) for c in rubric["criteria"])); criteria=_sub(re,"criteria")
        for criterion in rubric["criteria"]:
            ce=_sub(criteria,"criterion"); _sub(ce,"description",criterion["description"]); _sub(ce,"points",criterion["points"]); ratings=_sub(ce,"ratings")
            for rating in criterion["ratings"]:
                ra=_sub(ratings,"rating"); _sub(ra,"description",rating["description"]); _sub(ra,"points",rating["points"])
                if rating.get("long_description"): _sub(ra,"long_description",rating["long_description"])
    (work/"course_settings/rubrics.xml").write_bytes(_xml(rubrics))

    def add_resource(identifier, typ, href, files, dependency=None): resources.append((identifier,typ,href,files,dependency))
    # Pages, including a front-page syllabus when desired.
    for page in spec.get("pages",[]):
        slug=page.get("slug") or slugify(page["title"],100); rid=_id("respage",slug)
        body=_read(engine,page["body_file"]) if page.get("body_file") else page.get("body","")
        doc=(f'<!DOCTYPE html><html><head><meta charset="utf-8"><title>{page["title"]}</title>'
             f'<meta name="identifier" content="{rid}"><meta name="editing_roles" content="teachers">'
             f'<meta name="workflow_state" content="{"active" if page.get("published",False) else "unpublished"}">'
             f'</head><body>{body}</body></html>')
        rel=f"wiki_content/{slug}.html"; (work/rel).write_text(doc,encoding="utf-8")
        add_resource(rid,"webcontent",rel,[rel]); objects[page["key"]]={"id":rid,"title":page["title"],"type":"WikiPage"}

    # Native Canvas assignments.
    for pos,a in enumerate(spec.get("assignments",[]),1):
        aid=_id("as",a["key"]); folder=work/aid; folder.mkdir()
        body=_read(engine,a["description_file"]) if a.get("description_file") else a.get("description","")
        (folder/"assignment.html").write_text(body,encoding="utf-8")
        x=ET.Element("assignment",{"xmlns":CANVAS,"identifier":aid})
        for tag,val in [("title",a["title"]),("due_at",a.get("due_at","")),("lock_at",a.get("lock_at","")),
                        ("unlock_at",a.get("unlock_at","")),("module_locked","false")]: _sub(x,tag,val)
        if a.get("assignment_group"): _sub(x,"assignment_group_identifierref",group_ids[a["assignment_group"]])
        _sub(x,"workflow_state","published" if a.get("published",False) else "unpublished")
        if a.get("rubric"):
            _sub(x,"rubric_identifierref",rubric_ids[a["rubric"]]); _sub(x,"rubric_use_for_grading",str(a.get("rubric_use_for_grading",True)).lower())
        _sub(x,"points_possible",a.get("points",0)); _sub(x,"grading_type",a.get("grading_type","points"))
        _sub(x,"submission_types",",".join(a.get("submission_types",["none"])))
        _sub(x,"position",pos); _sub(x,"peer_reviews","false")
        (folder/"assignment_settings.xml").write_bytes(_xml(x))
        files=[f"{aid}/assignment.html",f"{aid}/assignment_settings.xml"]
        add_resource(aid,"associatedcontent/imscc_xmlv1p1/learning-application-resource",files[0],files)
        objects[a["key"]]={"id":aid,"title":a["title"],"type":"Assignment"}

    # Native discussion topics: IMS discussion body plus Canvas topic metadata.
    for pos,d in enumerate(spec.get("discussions",[]),1):
        did=_id("discussion",d["key"]); meta_id=_id("discussionmeta",d["key"])
        body=_read(engine,d["message_file"]) if d.get("message_file") else d.get("message","")
        topic=ET.Element("topic",{"xmlns":"http://www.imsglobal.org/xsd/imsccv1p1/imsdt_v1p1"})
        _sub(topic,"title",d["title"]); _sub(topic,"text",body,texttype="text/html"); (work/f"{did}.xml").write_bytes(_xml(topic))
        tm=ET.Element("topicMeta",{"xmlns":CANVAS,"identifier":meta_id}); _sub(tm,"topic_id",did); _sub(tm,"title",d["title"])
        if d.get("points") is not None:
            ae=_sub(tm,"assignment",identifier=_id("discussionassignment",d["key"])); _sub(ae,"title",d["title"])
            for tag,val in [("due_at",d.get("due_at","")),("lock_at",d.get("lock_at","")),("unlock_at",d.get("unlock_at","")),("module_locked","false")]: _sub(ae,tag,val)
            if d.get("assignment_group"): _sub(ae,"assignment_group_identifierref",group_ids[d["assignment_group"]])
            _sub(ae,"workflow_state","published" if d.get("published",False) else "unpublished")
            if d.get("rubric"): _sub(ae,"rubric_identifierref",rubric_ids[d["rubric"]]); _sub(ae,"rubric_use_for_grading","true")
            _sub(ae,"points_possible",d["points"]); _sub(ae,"grading_type","points"); _sub(ae,"submission_types","discussion_topic")
        for tag,val in [("position",pos),("type","topic"),("discussion_type",d.get("discussion_type","threaded")),
                        ("require_initial_post",str(d.get("require_initial_post",False)).lower()),
                        ("workflow_state","active" if d.get("published",False) else "unpublished"),("module_locked","false")]: _sub(tm,tag,val)
        (work/f"{meta_id}.xml").write_bytes(_xml(tm))
        add_resource(did,"imsdt_xmlv1p1",f"{did}.xml",[f"{did}.xml"],meta_id)
        add_resource(meta_id,"associatedcontent/imscc_xmlv1p1/learning-application-resource",f"{meta_id}.xml",[f"{meta_id}.xml"])
        objects[d["key"]]={"id":did,"title":d["title"],"type":"DiscussionTopic"}

    # Copy ordinary files into web_resources/ and expose them as resources.
    for f in spec.get("files",[]):
        src=resolve_path(engine,f["source"]); rel=f"web_resources/{f.get('name',src.name)}"
        (work/"web_resources").mkdir(exist_ok=True); shutil.copy2(src,work/rel)
        rid=_id("resfile",f["key"]); add_resource(rid,"webcontent",rel,[rel])
        objects[f["key"]]={"id":rid,"title":f.get("title",src.name),"type":"File"}

    # Module metadata plus matching Common Cartridge organization tree.
    mm=ET.Element("modules",{"xmlns":CANVAS})
    for mpos,m in enumerate(spec.get("modules",[]),1):
        mid=_id("mod",m["title"]); me=_sub(mm,"module",identifier=mid)
        _sub(me,"title",m["title"]); _sub(me,"workflow_state","active" if m.get("published",False) else "unpublished"); _sub(me,"position",mpos)
        ies=_sub(me,"items"); refs=[]
        for ipos,key in enumerate(m.get("items",[]),1):
            obj=objects[key]; iid=_id("item",m["title"]+key); ie=_sub(ies,"item",identifier=iid)
            for tag,val in [("content_type",obj["type"]),("workflow_state","active"),("title",obj["title"]),
                            ("identifierref",obj["id"]),("position",ipos),("indent",0)]: _sub(ie,tag,val)
            refs.append((iid,obj))
        module_refs.append((mid,m["title"],refs))
    (work/"course_settings/module_meta.xml").write_bytes(_xml(mm))

    manifest=ET.Element(f"{{{IMS}}}manifest",identifier=_id("manifest",title)); md=_sub(manifest,f"{{{IMS}}}metadata")
    _sub(md,f"{{{IMS}}}schema","IMS Common Cartridge"); _sub(md,f"{{{IMS}}}schemaversion","1.1.0")
    orgs=_sub(manifest,f"{{{IMS}}}organizations"); org=_sub(orgs,f"{{{IMS}}}organization",identifier="org_1",structure="rooted-hierarchy")
    rootitem=_sub(org,f"{{{IMS}}}item",identifier="LearningModules"); _sub(rootitem,f"{{{IMS}}}title","Modules")
    for mid,mtitle,refs in module_refs:
        mi=_sub(rootitem,f"{{{IMS}}}item",identifier=mid); _sub(mi,f"{{{IMS}}}title",mtitle)
        for iid,obj in refs:
            it=_sub(mi,f"{{{IMS}}}item",identifier=iid,identifierref=obj["id"]); _sub(it,f"{{{IMS}}}title",obj["title"])
    rs=_sub(manifest,f"{{{IMS}}}resources")
    course_files=["course_settings/course_settings.xml","course_settings/assignment_groups.xml","course_settings/canvas_export.txt","course_settings/module_meta.xml","course_settings/rubrics.xml"]
    cr=_sub(rs,f"{{{IMS}}}resource",identifier=course_id,type="associatedcontent/imscc_xmlv1p1/learning-application-resource",href=course_files[2])
    for f in course_files: _sub(cr,f"{{{IMS}}}file",href=f)
    for rid,typ,href,files,dependency in resources:
        re=_sub(rs,f"{{{IMS}}}resource",identifier=rid,type=typ,href=href)
        for f in files:_sub(re,f"{{{IMS}}}file",href=f)
        if dependency:_sub(re,f"{{{IMS}}}dependency",identifierref=dependency)
    (work/"imsmanifest.xml").write_bytes(_xml(manifest))

    # Stable ZIP order and timestamps: same spec/input bytes -> same IMSCC bytes.
    with zipfile.ZipFile(output,"w",zipfile.ZIP_DEFLATED) as z:
        for p in sorted(x for x in work.rglob("*") if x.is_file()):
            info=zipfile.ZipInfo(p.relative_to(work).as_posix(),(1980,1,1,0,0,0)); info.compress_type=zipfile.ZIP_DEFLATED
            z.writestr(info,p.read_bytes())
    summary={"course":title,"pages":len(spec.get("pages",[])),"assignments":len(spec.get("assignments",[])),"discussions":len(spec.get("discussions",[])),"rubrics":len(spec.get("rubrics",[])),"modules":len(spec.get("modules",[])),"files":len(spec.get("files",[]))}
    (work/"build-summary.json").write_text(json.dumps(summary,indent=2)); return summary
