#!/usr/bin/env python3
"""Initialize the toolkit's one target-course config from a pasted Canvas URL."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from canvas_automation import jsonc


def parse_course_url(value: str) -> tuple[str, int]:
    match = re.fullmatch(r"(https://[^/]+)/courses/([1-9][0-9]*)/?(?:[?#].*)?", value.strip())
    if not match:
        raise ValueError("Paste a full HTTPS Canvas course URL such as https://canvas.example.edu/courses/12345")
    return match.group(1), int(match.group(2))


def ask(value: str | None, prompt: str, default: str = "") -> str:
    if value is not None:
        return value.strip()
    suffix = f" [{default}]" if default else ""
    entered = input(f"{prompt}{suffix}: ").strip()
    return entered or default


def update_command_configs(root: Path, course_url: str, course_id: int) -> list[str]:
    changed = []
    for path in sorted((root / "commands").glob("*.config.jsonc")):
        text = path.read_text(encoding="utf-8")
        updated = re.sub(r'("course_id"\s*:\s*)\d+', rf"\g<1>{course_id}", text)
        if path.name == "start-server.config.jsonc":
            updated = re.sub(r'("sandbox_course_url"\s*:\s*)"[^"]+"', rf'\g<1>"{course_url}"', updated)
        if updated != text:
            path.write_text(updated, encoding="utf-8")
            changed.append(path.relative_to(root).as_posix())
    return changed


def update_course_manifests(root: Path, course_id: int) -> list[str]:
    """Keep course-bound manifests aligned with the single initialized target."""
    changed = []
    for relative in ("course/rubric-manifest.json",):
        path = root / relative
        if not path.exists():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        if data.get("course_id") == course_id:
            continue
        data["course_id"] = course_id
        path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        changed.append(relative)
    return changed


def initialize(root: Path, args) -> dict:
    course_url = ask(args.course_url, "Canvas course URL")
    base_url, course_id = parse_course_url(course_url)
    host = urlparse(base_url).hostname or ""
    institution_name = ask(args.institution_name, "Institution name", host)
    institution_homepage = ask(args.institution_homepage, "Institution homepage", base_url + "/")
    policy_domain = ask(args.policy_domain, "Primary domain for institutional policy research", host.removeprefix("canvas."))
    library_host = ask(args.library_resolver_host, "Library search/resolver host (optional)", "")
    config_path = root / "course/course.config.jsonc"
    previous = jsonc.load_jsonc(config_path) if config_path.exists() else {}
    authoring = previous.get("authoring", {
        "manifest": "course/course-manifest.json", "links_manifest": "course/links-manifest.json", "imscc_template": ""
    })
    config = {
        "course_url": course_url.rstrip("/"),
        "institution": {
            "name": institution_name, "homepage": institution_homepage, "canvas_host": host,
            "policy_search_domains": [policy_domain] if policy_domain else [],
            "library_resolver_hosts": [library_host] if library_host else [],
        },
        "authoring": authoring,
    }
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text("// Generated by scripts/initialize_toolkit.py; contains no credentials.\n" + json.dumps(config, indent=2) + "\n", encoding="utf-8")
    changed = update_command_configs(root, config["course_url"], course_id)
    manifests = update_course_manifests(root, course_id)
    return {"course_id": course_id, "course_url": config["course_url"], "course_config": "course/course.config.jsonc", "updated_command_configs": changed, "updated_course_manifests": manifests, "next": ["Start the guarded server", "Run course_authoring.py export-live --initialize", "Ask an AI to use $configure-canvas-course"]}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--course-url")
    parser.add_argument("--institution-name")
    parser.add_argument("--institution-homepage")
    parser.add_argument("--policy-domain")
    parser.add_argument("--library-resolver-host")
    args = parser.parse_args()
    print(json.dumps(initialize(args.root.resolve(), args), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
